### ISSUE TITLE
panic when parsing fake pnpm lockfile

### ISSUE THREAD

**Issue by laurentS** [google/osv-scanner#364]
While running ossf scorecard on https://github.com/parcel-bundler/parcel, which calls osv-scanner, it panicked on the following lockfile https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/integration/resolve-symlinked-monorepos/pnpm-lock.yaml

with the following traceback (narrowed down to the culprit):

```
go run github.com/google/osv-scanner/cmd/osv-scanner@v1 --lockfile=packages/core/integration-tests/test/integration/resolve-symlinked-monorepos/pnpm-lock.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c11e2]

goroutine 1 [running]:
github.com/google/osv-scanner/pkg/lockfile.ParsePnpmLock({0xc000158c80, 0x7b})
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/pkg/lockfile/parse-pnpm-lock.go:181 +0x202
github.com/google/osv-scanner/pkg/lockfile.Parse({0xc000158c80, 0x7b}, {0xc00003f6e0, 0x0})
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/pkg/lockfile/parse.go:141 +0x29f
github.com/google/osv-scanner/pkg/osvscanner.scanLockfile({0xd4b8a0, 0xc0001b5680}, 0xc000012db0, {0xc000158c80, 0x7b}, {0xc00003f6e0, 0x0})
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/pkg/osvscanner/osvscanner.go:196 +0x21f
github.com/google/osv-scanner/pkg/osvscanner.DoScan({{0xc0001a7bd0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x11dab10, 0x0, 0x0}, {0x0, ...}, ...}, ...)
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/pkg/osvscanner/osvscanner.go:503 +0x236
main.run.func3(0xc0001b2740)
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/cmd/osv-scanner/main.go:123 +0x698
github.com/urfave/cli/v2.(*Command).Run(0xc000126840, 0xc0001b2740, {0xc000036040, 0x2, 0x2})
        path/to/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0xa42
github.com/urfave/cli/v2.(*App).RunContext(0xc0001ca1e0, {0xd4b3d0?, 0xc00003c108}, {0xc000036040, 0x2, 0x2})
        path/to/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        path/to/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
main.run({0xc000036040, 0x2, 0x2}, {0xd45640?, 0xc000014018}, {0xd45640?, 0xc000014020})
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/cmd/osv-scanner/main.go:143 +0xa7e
main.main()
        path/to/go/pkg/mod/github.com/google/osv-scanner@v1.3.2/cmd/osv-scanner/main.go:174 +0x46
exit status 2
```

I'm not familiar with pnpm, but I'm assuming the format is invalid. My guess is that `osv-scanner` should probably log a warning or similar, but continue running, as it's unlikely the user (me in this case) can fix the input.

This is with `osv-scanner@v1.3.2`.

**Comment by oliverchang** [comment]
@michaelkedar mind taking a look to see if we can exit more cleanly here?

**Comment by G-Rath** [comment]
fyi I've fixed this in the detector so you can just cherry-pick that (or I can later today if you like): https://github.com/G-Rath/osv-detector/pull/191

**Comment by oliverchang** [comment]
Ah, if you can create a PR later today, that would be great :) Thanks @G-Rath !
